export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const SET_AUTHENTICATION_SUCCESS = 'SET_AUTHENTICATION_SUCCESS';
export const SET_AUTHENTICATION_FAILURE = 'SET_AUTHENTICATION_FAILURE';

export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const GET_AUTH_FAILURE = 'GET_AUTH_FAILURE';

export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_FAILURE = 'SET_REGISTER_FAILURE';
