export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const SET_AUTHENTICATION_SUCCESS = 'SET_AUTHENTICATION_SUCCESS';
export const SET_AUTHENTICATION_FAILURE = 'SET_AUTHENTICATION_FAILURE';

export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS';
export const GET_AUTH_FAILURE = 'GET_AUTH_FAILURE';

export const SET_REGISTER_SUCCESS = 'SET_REGISTER_SUCCESS';
export const SET_REGISTER_FAILURE = 'SET_REGISTER_FAILURE';

export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS';
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE';

export const ADD_INVOICE_USER_DATA_SUCCESS = 'ADD_INVOICE_USER_DATA_SUCCESS';
export const ADD_INVOICE_USER_DATA_FAILURE = 'ADD_INVOICE_USER_DATA_FAILURE';

//create expense tracker
export const ADD_EXPENSE_TRANSACTION_SUCCESS = 'ADD_EXPENSE_TRANSACTION_SUCCESS';
export const ADD_EXPENSE_TRANSACTION_FAILURE = 'ADD_EXPENSE_TRANSACTION_FAILURE';
//get expense tracker
export const GET_EXPENSE_TRANSACTION_SUCCESS = 'GET_EXPENSE_TRANSACTION_SUCCESS';
export const GET_EXPENSE_TRANSACTION_FAILURE = 'GET_EXPENSE_TRANSACTION_FAILURE';
//delete expense tracker
export const DELETE_EXPENSE_TRANSACTION_SUCCESS = 'DELETE_EXPENSE_TRANSACTION_SUCCESS';
export const DELETE_EXPENSE_TRANSACTION_FAILURE = 'DELETE_EXPENSE_TRANSACTION_FAILURE';