export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const SET_AUTHENTICATION_SUCCESS = 'SET_AUTHENTICATION_SUCCESS';
export const SET_AUTHENTICATION_FAILURE = 'GET_AUTHENTICATION_FAILURE';
